name: Publish Package

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch
    tags:
      - 'v*.*.*'  # Trigger on tag pushes with version numbers

jobs:
  build:
    runs-on: ubuntu-latest  # Directly specify the OS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build twine

      - name: Build package
        run: |
          docker build -t ominis -f Dockerfile .
          docker run ominis  # Adapt as necessary

      - name: Publish to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*
