name: Publish Package

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch
    tags:
      - 'v*.*.*'  # Optionally trigger on tag pushes with version numbers

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build twine

      - name: Build package
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            docker build -t ominis -f Dockerfile . && docker run ominis
          else
            python -m build
          fi

      - name: Publish to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*
