name: Search username

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to search'
        required: true
      include_titles:
        description: 'Include titles in results'
        required: true
        type: boolean
        default: true
      include_descriptions:
        description: 'Include descriptions in results'
        required: true
        type: boolean
        default: true
      include_html:
        description: 'Include HTML content in results'
        required: true
        type: boolean
        default: false

jobs:
  username-search:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install -r requirements.txt

      - name: Create Results directory
        run: |
          sudo mkdir -p Results
          sudo chmod 777 Results

      - name: Create input simulation script
        run: |
          sudo bash -c 'cat > input_sim.py << EOL
          def mock_input(prompt):
              import os
              if "Include titles" in prompt:
                  return "y" if os.environ.get("INCLUDE_TITLES", "false").lower() == "true" else "n"
              if "Include descriptions" in prompt:
                  return "y" if os.environ.get("INCLUDE_DESCRIPTIONS", "false").lower() == "true" else "n"
              if "Include HTML content" in prompt:
                  return "y" if os.environ.get("INCLUDE_HTML", "false").lower() == "true" else "n"
              return ""

          import builtins
          builtins.input = mock_input
          EOL'
          sudo chmod 666 input_sim.py

      - name: Run username search
        env:
          INCLUDE_TITLES: ${{ github.event.inputs.include_titles }}
          INCLUDE_DESCRIPTIONS: ${{ github.event.inputs.include_descriptions }}
          INCLUDE_HTML: ${{ github.event.inputs.include_html }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          sudo python -c "
          import input_sim
          from src.usr import main
          main('${{ github.event.inputs.username }}')
          "

      - name: Upload search results
        uses: actions/upload-artifact@v4
        with:
          name: username-search-results
          path: |
            Results/username-search_results.txt
            src/username_search.log
