name: Search username

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to search'
        required: true
      include_titles:
        description: 'Include titles in results'
        required: true
        type: boolean
        default: true
      include_descriptions:
        description: 'Include descriptions in results'
        required: true
        type: boolean
        default: true
      include_html:
        description: 'Include HTML content in results'
        required: true
        type: boolean
        default: false

jobs:
  username-search:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y tor

      - name: Start Tor service
        run: |
          sudo service tor start
          sudo timeout 30 tail -f /var/log/tor/log || true

      - name: Create Results directory
        run: |
          sudo mkdir -p Results
          sudo chmod 777 Results

      - name: Create proxy configuration
        run: |
          sudo bash -c 'cat > proxy_config.py << EOL
          import aiohttp
          from aiohttp_socks import ProxyConnector
          import asyncio
          import random
          import time
          import subprocess

          last_rotation = 0
          ROTATION_INTERVAL = 60  # 1 min in sec

          async def get_tor_session():
              connector = ProxyConnector.from_url("socks5://127.0.0.1:9050")
              return aiohttp.ClientSession(connector=connector)

          async def rotate_tor_identity():
              global last_rotation
              current_time = time.time()
              
              if current_time - last_rotation >= ROTATION_INTERVAL:
                  try:
                      subprocess.run(["sudo", "killall", "-HUP", "tor"])
                      await asyncio.sleep(random.uniform(2, 4))
                      last_rotation = current_time
                      print("🔄 Rotated Tor identity")
                  except Exception as e:
                      print(f"Failed to rotate Tor identity: {e}")
                      pass

          async def check_and_rotate():
              while True:
                  await rotate_tor_identity()
                  await asyncio.sleep(10)
          EOL'
          sudo chmod 666 proxy_config.py

      - name: Configure Tor control
        run: |
          sudo bash -c 'echo "ControlPort 9051" >> /etc/tor/torrc'
          sudo bash -c 'echo "CookieAuthentication 1" >> /etc/tor/torrc'
          sudo service tor restart
          sudo timeout 30 tail -f /var/log/tor/log || true

      - name: Create input simulation script
        run: |
          sudo bash -c 'cat > input_sim.py << EOL
          def mock_input(prompt):
              import os
              if "proxy rotation display" in prompt.lower():
                  return "y"
              if "Include titles" in prompt:
                  return "y" if os.environ.get("INCLUDE_TITLES", "false").lower() == "true" else "n"
              if "Include descriptions" in prompt:
                  return "y" if os.environ.get("INCLUDE_DESCRIPTIONS", "false").lower() == "true" else "n"
              if "Include HTML content" in prompt:
                  return "y" if os.environ.get("INCLUDE_HTML", "false").lower() == "true" else "n"
              return ""

          import builtins
          builtins.input = mock_input
          EOL'
          sudo chmod 666 input_sim.py

      - name: Run username search
        env:
          INCLUDE_TITLES: ${{ github.event.inputs.include_titles }}
          INCLUDE_DESCRIPTIONS: ${{ github.event.inputs.include_descriptions }}
          INCLUDE_HTML: ${{ github.event.inputs.include_html }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          sudo python -c "
          import input_sim
          import asyncio
          import proxy_config
          from src.usr import main

          async def run_search():
              rotation_task = asyncio.create_task(proxy_config.check_and_rotate())
              try:
                  main('${{ github.event.inputs.username }}')
              finally:
                  rotation_task.cancel()

          asyncio.run(run_search())
          "

      - name: Upload search results
        uses: actions/upload-artifact@v4
        with:
          name: username-search-results
          path: |
            results/username-search_results.txt
            src/username_search.log
