name: Web Search

on:
  workflow_dispatch:
    inputs:
      query:
        description: 'Search query'
        required: true
      language:
        description: 'Language code (e.g., lang_en)'
        required: false
        default: 'lang_en'
      country:
        description: 'Country code (e.g., US)'
        required: false
        default: 'US'
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: false
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: false

jobs:
  web-search:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install -r requirements.txt

      - name: Create search script
        run: |
          sudo bash -c 'cat > run_search.py << EOL
          import asyncio
          import sys
          from src.tools_handler import fetch_google_results
          from src.proxy_handler import scrape_proxies, validate_proxies

          async def main():
              query = sys.argv[1]
              language = sys.argv[2]
              country = sys.argv[3]
              date_range = (sys.argv[4], sys.argv[5]) if sys.argv[4] and sys.argv[5] else None
              
              proxies = await scrape_proxies()
              valid_proxies = await validate_proxies(proxies)
              
              results = await fetch_google_results(
                  query=query,
                  language=language,
                  country=country,
                  date_range=date_range,
                  proxies=valid_proxies
              )
              return results

          if __name__ == "__main__":
              asyncio.run(main())
          EOL'

          sudo chmod 666 run_search.py

      - name: Run web search
        run: |
          sudo python run_search.py "${{ github.event.inputs.query }}" \
                              "${{ github.event.inputs.language }}" \
                              "${{ github.event.inputs.country }}" \
                              "${{ github.event.inputs.start_date }}" \
                              "${{ github.event.inputs.end_date }}"

      - name: Upload search results
        uses: actions/upload-artifact@v4
        with:
          name: search-results
          path: |
            results/*.txt
            logs/gfetcherror.log 
